package com.qxt.bysj.domain;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tag.tagname
     *
     * @mbggenerated
     */
    private String tagname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tag.id
     *
     * @return the value of tab_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tag.id
     *
     * @param id the value for tab_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tag.tagname
     *
     * @return the value of tab_tag.tagname
     *
     * @mbggenerated
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tag.tagname
     *
     * @param tagname the value for tab_tag.tagname
     *
     * @mbggenerated
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }
}