package com.qxt.bysj.domain;

public class TagXvideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tagxvideo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tagxvideo.tagId
     *
     * @mbggenerated
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tagxvideo.videoId
     *
     * @mbggenerated
     */
    private Integer videoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tagxvideo.id
     *
     * @return the value of tab_tagxvideo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tagxvideo.id
     *
     * @param id the value for tab_tagxvideo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tagxvideo.tagId
     *
     * @return the value of tab_tagxvideo.tagId
     *
     * @mbggenerated
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tagxvideo.tagId
     *
     * @param tagid the value for tab_tagxvideo.tagId
     *
     * @mbggenerated
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tagxvideo.videoId
     *
     * @return the value of tab_tagxvideo.videoId
     *
     * @mbggenerated
     */
    public Integer getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tagxvideo.videoId
     *
     * @param videoid the value for tab_tagxvideo.videoId
     *
     * @mbggenerated
     */
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }
}