package com.qxt.bysj.domain;

public class TagXuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tagxuser.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tagxuser.tagId
     *
     * @mbggenerated
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_tagxuser.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    private Integer hot;

    public Integer getHot() {
        return hot;
    }

    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tagxuser.id
     *
     * @return the value of tab_tagxuser.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tagxuser.id
     *
     * @param id the value for tab_tagxuser.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tagxuser.tagId
     *
     * @return the value of tab_tagxuser.tagId
     *
     * @mbggenerated
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tagxuser.tagId
     *
     * @param tagid the value for tab_tagxuser.tagId
     *
     * @mbggenerated
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_tagxuser.userId
     *
     * @return the value of tab_tagxuser.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_tagxuser.userId
     *
     * @param userid the value for tab_tagxuser.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}